-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgE9j1CsW9sX0ECq0j
TSzHRpTl5GZ5aSMbjJTWjpXgFjygCgYIKoZIzj0DAQehRANCAAShKE/NsOtHPCjj
OiEmhvOC2fbALWEh6tRSalgOfKva7YKmuDSxYplyB8+kDpy9gbgmGOZ18NUbBs8D
LTvK4kpx
-----END PRIVATE KEY-----