version: '3.3'

services:
  #  API SERVICE
  makinginvest-python-api:
    build: .
    image: makinginvest-python-api
    container_name: makinginvest-python-api
    ports:
      - 8072:8072
    restart: unless-stopped
    networks:
      - traefik-network
    environment:
      - ALLOW_CRON=False
      - PRODUCTION=True
      - DATA_MODE=False
      - WEBSOCKET_MODE=False
      - API_MODE=True
      - PORT=8072
      - WORKERS=1
      - HOST=0.0.0.0
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.makinginvest-python-api.rule=Host(`makinginvest-server-python-api-api-v1.makinginvest.com`)'
      - 'traefik.http.routers.makinginvest-python-api.entrypoints=websecure'
      - 'traefik.http.routers.makinginvest-python-api.tls.certresolver=myresolver'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)'
      - 'traefik.http.routers.redirs.entrypoints=web'
      - 'traefik.http.routers.redirs.middlewares=redirect-to-https'
    volumes:
      - '/root/vol-logs:/usr/src/app/logs/'

  #  DATA SERVICE
  makinginvest-python-data:
    build: .
    image: makinginvest-python-data
    container_name: makinginvest-python-data
    ports:
      - 8070:8070
    restart: unless-stopped
    networks:
      - traefik-network
    environment:
      - ALLOW_CRON=True
      - PRODUCTION=True
      - DATA_MODE=True
      - PORT=8070
      - WORKERS=1
      - HOST=0.0.0.0
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.makinginvest-python-data.rule=Host(`makinginvest-server-python-api-data-v1.makinginvest.com`)'
      - 'traefik.http.routers.makinginvest-python-data.entrypoints=websecure'
      - 'traefik.http.routers.makinginvest-python-data.tls.certresolver=myresolver'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)'
      - 'traefik.http.routers.redirs.entrypoints=web'
      - 'traefik.http.routers.redirs.middlewares=redirect-to-https'
    volumes:
      - '/root/vol-logs:/usr/src/app/logs/'

  #  WEBSOCKET
  makinginvest-python-websocket:
    build: .
    image: makinginvest-python-websocket
    container_name: makinginvest-python-websocket
    ports:
      - 8071:8071
    restart: unless-stopped
    networks:
      - traefik-network
    environment:
      - ALLOW_CRON=False
      - PRODUCTION=True
      - DATA_MODE=False
      - WEBSOCKET_MODE=True
      - PORT=8071
      - WORKERS=1
      - HOST=0.0.0.0
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.makinginvest-python-websocket.rule=Host(`makinginvest-server-python-api-websocket-v1.makinginvest.com`)'
      - 'traefik.http.routers.makinginvest-python-websocket.entrypoints=websecure'
      - 'traefik.http.routers.makinginvest-python-websocket.tls.certresolver=myresolver'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)'
      - 'traefik.http.routers.redirs.entrypoints=web'
      - 'traefik.http.routers.redirs.middlewares=redirect-to-https'
    volumes:
      - '/root/vol-logs:/usr/src/app/logs/'

  #  Main SERVICE
  makinginvest-python-engines-main:
    build: .
    image: makinginvest-python-engines-main
    container_name: makinginvest-python-engines-main
    ports:
      - 8073:8073
    restart: unless-stopped
    networks:
      - traefik-network
    environment:
      - ALLOW_CRON=True
      - PRODUCTION=True
      - DATA_MODE=False
      - PORT=8073
      - WORKERS=1
      - HOST=0.0.0.0
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.makinginvest-python-engines-main.rule=Host(`makinginvest-server-python-api-engines-main-v1.makinginvest.com`)'
      - 'traefik.http.routers.makinginvest-python-engines-main.entrypoints=websecure'
      - 'traefik.http.routers.makinginvest-python-engines-main.tls.certresolver=myresolver'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)'
      - 'traefik.http.routers.redirs.entrypoints=web'
      - 'traefik.http.routers.redirs.middlewares=redirect-to-https'
    volumes:
      - '/root/vol-logs:/usr/src/app/logs/'

  #  Engines crypto SERVICE
  makinginvest-python-engines-all:
    build: .
    image: makinginvest-python-engines-all
    container_name: makinginvest-python-engines-all
    ports:
      - 8074:8074
    restart: unless-stopped
    networks:
      - traefik-network
    environment:
      - ALLOW_CRON=False
      - PRODUCTION=True
      - DATA_MODE=False
      - PORT=8074
      - WORKERS=16
      - HOST=0.0.0.0
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.makinginvest-python-engines-all.rule=Host(`makinginvest-server-python-api-engines-all-v1.makinginvest.com`)'
      - 'traefik.http.routers.makinginvest-python-engines-all.entrypoints=websecure'
      - 'traefik.http.routers.makinginvest-python-engines-all.tls.certresolver=myresolver'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)'
      - 'traefik.http.routers.redirs.entrypoints=web'
      - 'traefik.http.routers.redirs.middlewares=redirect-to-https'
    volumes:
      - '/root/vol-logs:/usr/src/app/logs/'

networks:
  traefik-network:
    external: true
