version: '3.3'

services:
  #  API SERVICE
  makinginvest-python-api:
    build: .
    image: makinginvest-python-api
    container_name: makinginvest-python-api
    ports:
      - 8072:8072
    restart: unless-stopped
    networks:
      - traefik-network
    environment:
      - ALLOW_CRON=False
      - PRODUCTION=True
      - WEBSOCKET_MODE=False
      - API_MODE=True
      - PORT=8072
      - WORKERS=1
      - HOST=0.0.0.0
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.makinginvest-python-api.rule=Host(`makinginvest-server-python-api-v1.api.makinginvest.com`)'
      - 'traefik.http.routers.makinginvest-python-api.entrypoints=websecure'
      - 'traefik.http.routers.makinginvest-python-api.tls.certresolver=myresolver'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)'
      - 'traefik.http.routers.redirs.entrypoints=web'
      - 'traefik.http.routers.redirs.middlewares=redirect-to-https'
    volumes:
      - '/root/vol-logs:/usr/src/app/logs/'

  #  WEBSOCKET
  makinginvest-python-api-websocket:
    build: .
    image: makinginvest-python-api-websocket
    container_name: makinginvest-python-api-websocket
    ports:
      - 8071:8071
    restart: unless-stopped
    networks:
      - traefik-network
    environment:
      - ALLOW_CRON=False
      - PRODUCTION=True
      - WEBSOCKET_MODE=True
      - PORT=8071
      - WORKERS=1
      - HOST=0.0.0.0
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.makinginvest-python-api-websocket.rule=Host(`makinginvest-server-python-api-websocket-v1.api.makinginvest.com`)'
      - 'traefik.http.routers.makinginvest-python-api-websocket.entrypoints=websecure'
      - 'traefik.http.routers.makinginvest-python-api-websocket.tls.certresolver=myresolver'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)'
      - 'traefik.http.routers.redirs.entrypoints=web'
      - 'traefik.http.routers.redirs.middlewares=redirect-to-https'
    volumes:
      - '/root/vol-logs:/usr/src/app/logs/'

  #  Main SERVICE
  makinginvest-python-engines-driver:
    build: .
    image: makinginvest-python-engines-driver
    container_name: makinginvest-python-engines-driver
    ports:
      - 8073:8073
    restart: unless-stopped
    networks:
      - traefik-network
    environment:
      - ALLOW_CRON=True
      - PRODUCTION=True
      - PORT=8073
      - WORKERS=1
      - HOST=0.0.0.0
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.makinginvest-python-engines-driver.rule=Host(`makinginvest-server-python-api-engines-driver-v1.api.makinginvest.com`)'
      - 'traefik.http.routers.makinginvest-python-engines-driver.entrypoints=websecure'
      - 'traefik.http.routers.makinginvest-python-engines-driver.tls.certresolver=myresolver'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)'
      - 'traefik.http.routers.redirs.entrypoints=web'
      - 'traefik.http.routers.redirs.middlewares=redirect-to-https'
    volumes:
      - '/root/vol-logs:/usr/src/app/logs/'

  #  Engines crypto SERVICE
  makinginvest-python-engines-worker:
    build: .
    image: makinginvest-python-engines-worker
    container_name: makinginvest-python-engines-worker
    ports:
      - 8074:8074
    restart: unless-stopped
    networks:
      - traefik-network
    environment:
      - ALLOW_CRON=False
      - PRODUCTION=True
      - PORT=8074
      - WORKERS=16
      - HOST=0.0.0.0
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.makinginvest-python-engines-worker.rule=Host(`makinginvest-server-python-api-engines-worker-v1.api.makinginvest.com`)'
      - 'traefik.http.routers.makinginvest-python-engines-worker.entrypoints=websecure'
      - 'traefik.http.routers.makinginvest-python-engines-worker.tls.certresolver=myresolver'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)'
      - 'traefik.http.routers.redirs.entrypoints=web'
      - 'traefik.http.routers.redirs.middlewares=redirect-to-https'
    volumes:
      - '/root/vol-logs:/usr/src/app/logs/'

networks:
  traefik-network:
    external: true
